#!/bin/bash

# get repo name
REPO_NAME=$(echo ${TRAVIS_REPO_SLUG} | cut -d"/" -f2)

# get tag and use it as a version
VERSION="${TRAVIS_TAG:1}"

# move to buildroot root
cd ~/buildroot

# create one defconfig per output type (gz,bz2,xz,...)
bash -e defconfig-per-output-splitter

# loop over rendered defconfigs
for i in .defconfig.rendered.*; do
  # compile & output 
  make defconfig BR2_DEFCONFIG=${i}
  make 2> ~/stderr.${i}.log | \tee ~/stdout.${i}.log | grep -i -e "^.*:" | grep -v "gcc" | grep -v "g++"
done

# rename files
outpath=output/images
for i in $outpath/rootfs*; do
  bn=$(basename ${i})
  mv ${i} ${outpath}/${REPO_NAME}-$V{ERSION}-${bn}
done
