sudo: false
language: bash
env:
  global:
    - BR_RELEASE=2015.08-rc1.rev2
addons:
  apt:
    packages:
    - build-essential
    - libncurses5-dev
    - rsync
    - cpio
    - python
    - unzip
    - bc
    - wget
install:
  - bash -e $(dirname $(readlink -f $TRAVIS_BUILD_DIR/.travis.yml))/install
script:
  - bash -e $(dirname $(readlink -f $TRAVIS_BUILD_DIR/.travis.yml))/script
after_failure:
  - tail -30 ~/stderr.*.log
  - tail -30 ~/stdout.*.log
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "rcP1REodqFw3kHMdPUc0jEonDOi8qEacu2Nh7TMN2arcsbeLYHd1Azpgg5P9gxftYdz1RZCHPImwi1zjI1Nl1ZyGQ5JDaMW7wYVVPr1EjJ9OInlHDJjsZp4y9MVp6mShH7y0NAqrSMuhKPWKVs4iEZzvwy1WUbKxJlvQ5K1ddcx1zbGYLSFAFfeOPAGfxCPYFEaTwsJjPhR3SxjGEuhaxbS1FQSNn5eSjJ6oaqVQ/9SF+Xzu04k1SipdIIgu4a2OvDAxcDQuqBBTWFfdrtz9Gp5arzYeCvW5S8RJH+kM88NtVeEiWdOGxwW4rdOfmHJdgErIvdxFEZno8KyxEWNBjIjPB9ylJwGAHN19GcI2Mk6msT2Iddwxn0ZPP8mdYa4wsIY0+uoAxfCtN62HTCup6mV9T5bBoXT3efcT0fbezNkp6soPMsEiS21caLqESgfn/7+rUlZXWDAhhEEUW8C/RNT55qwHU+VGPov29KCjlcpbp3m9ig2UXppXCBxebopzFDcYJzApfBtkFhSVTlozIWKeEeVHLEjGvFugNYV6TLkSjGUdgZJJuLo9q5mLLn91SaEESq84bWlTOLuNcPvARZwnJnJMx+bxjeXV3A/FohaLlqjKBL3bEYhVTe0QVeI3JJ4C+81i2N13t+vUQ3JmqKOwae1VtYt0luje+L2ule4="
  file:
    - ~/buildroot/output/images/*-rootfs.*
  file_glob: true
  on:
    repo: $TRAVIS_REPO_SLUG
    branch: master
    tags: true
