sudo: false
language: bash
env:
  global:
    - BR_RELEASE=2015.08-rc1.rev2
    - ROOTFS=~/buildroot/output/images/rootfs
addons:
  apt:
    packages:
    - build-essential
    - libncurses5-dev
    - rsync
    - cpio
    - python
    - unzip
    - bc
    - wget
install:
  - cd ~
  - cat $TRAVIS_BUILD_DIR/.travis.yml
  - echo "<== FOLLOW DIRNAME START ==>"; dirname $(readlink -f $TRAVIS_BUILD_DIR/.travis.yml); echo "<== FOLLOW DIRNAME END ==>"
  - wget -nv https://github.com/glerchundi/buildroot/releases/download/v$BR_RELEASE/buildroot-$BR_RELEASE.tar.bz2
  - tar xf buildroot-*.tar*
  - rm buildroot-*.tar*
  - ln -s buildroot-* buildroot
  - cp $TRAVIS_BUILD_DIR/defconfig ~/buildroot/.defconfig
script:
  - cd ~/buildroot
  - bash defconfig-per-output-splitter
  - for i in .defconfig.rendered.*; do make defconfig BR2_DEFCONFIG=$i && make 2> ~/stderr.log | tee ~/stdout.log | grep -i -e "^.*:" | grep -v "gcc" | grep -v "g++"; done
after_failure:
  - tail -30 ~/stderr.log
  - tail -30 ~/stdout.log
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "rcP1REodqFw3kHMdPUc0jEonDOi8qEacu2Nh7TMN2arcsbeLYHd1Azpgg5P9gxftYdz1RZCHPImwi1zjI1Nl1ZyGQ5JDaMW7wYVVPr1EjJ9OInlHDJjsZp4y9MVp6mShH7y0NAqrSMuhKPWKVs4iEZzvwy1WUbKxJlvQ5K1ddcx1zbGYLSFAFfeOPAGfxCPYFEaTwsJjPhR3SxjGEuhaxbS1FQSNn5eSjJ6oaqVQ/9SF+Xzu04k1SipdIIgu4a2OvDAxcDQuqBBTWFfdrtz9Gp5arzYeCvW5S8RJH+kM88NtVeEiWdOGxwW4rdOfmHJdgErIvdxFEZno8KyxEWNBjIjPB9ylJwGAHN19GcI2Mk6msT2Iddwxn0ZPP8mdYa4wsIY0+uoAxfCtN62HTCup6mV9T5bBoXT3efcT0fbezNkp6soPMsEiS21caLqESgfn/7+rUlZXWDAhhEEUW8C/RNT55qwHU+VGPov29KCjlcpbp3m9ig2UXppXCBxebopzFDcYJzApfBtkFhSVTlozIWKeEeVHLEjGvFugNYV6TLkSjGUdgZJJuLo9q5mLLn91SaEESq84bWlTOLuNcPvARZwnJnJMx+bxjeXV3A/FohaLlqjKBL3bEYhVTe0QVeI3JJ4C+81i2N13t+vUQ3JmqKOwae1VtYt0luje+L2ule4="
  file:
    - $ROOTFS.*
  file_glob: true
  on:
    repo: $TRAVIS_REPO_SLUG
    branch: master
    tags: true
