#!/bin/bash

# move to buildroot root
cd ~/buildroot

# create one defconfig per output type (gz,bz2,xz,...)
bash -e defconfig-per-output-splitter

# loop over rendered defconfigs
for i in .defconfig.rendered.*; do
  # compile & output 
  make defconfig BR2_DEFCONFIG=${i}
  make 2> ~/stderr.${i}.log | \tee ~/stdout.${i}.log | grep -i -e "^.*:" | grep -v "gcc" | grep -v "g++"
done

# exit if TRAVIS_TAG is empty, no need to release anything
if [ -z "${TRAVIS_TAG}" ]; then
  exit 0
fi

# get repo name & version
REPONAME=$(echo ${TRAVIS_REPO_SLUG} | cut -d"/" -f2)
VERSION="${TRAVIS_TAG:1}"

# rename files
outpath=output/images
for i in $outpath/rootfs*; do
  bn=$(basename ${i})
  mv ${i} ${outpath}/${REPONAME}-${VERSION}-${bn}
done
